const TODO_ACTION_ENUM = {
  ADD: "ADD_ITEM",
  DELETE: "DELETE_ITEM",
  CHANGE_TASK_STATUS: "TASK_STATUS_CHANGE",
  CLEAR_COMPLETED_TASKS: "CLEAR_COMPLETED_TASKS",
};

export default TODO_ACTION_ENUM;
